# Generated by Django 5.2.13 on 2026-04-20 10:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_frequency_norm_days', models.IntegerField(default=14, help_text='Default days before a farmer visit is considered overdue')),
                ('planner_refresh_hour', models.IntegerField(default=6, help_text='Hour (0-23) when daily smart planner refreshes')),
                ('msg91_auth_key', models.CharField(blank=True, max_length=255, null=True)),
                ('interakt_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('cloudinary_url', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Configuration',
                'verbose_name_plural': 'App Configuration',
            },
        ),
        migrations.CreateModel(
            name='CropMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=255)),
                ('crop_category', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_schedule_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('reference_image', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('field_changed', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Export', 'Export'), ('Login', 'Login'), ('Logout', 'Logout'), ('BulkImport', 'Bulk Import')], max_length=50)),
            ],
            options={
                'permissions': [('can_view_audit_log', 'Can view audit log')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('FieldStaff', 'Field Staff'), ('TerritoryManager', 'Territory Manager'), ('ZonalManager', 'Zonal Manager'), ('Admin', 'Admin'), ('ContentTeam', 'Content Team')], default='FieldStaff', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active', max_length=20)),
                ('device_push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_otp_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=255)),
                ('sequence_number', models.IntegerField()),
                ('days_from_previous_stage', models.IntegerField(default=0)),
                ('stage_description', models.TextField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.cropmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=255)),
                ('typical_duration_days', models.IntegerField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='core.cropmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('primary_mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('village', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Marathi', 'Marathi')], default='English', max_length=50)),
                ('land_holding_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('farmer_photo', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('BulkImport', 'Bulk Import'), ('InApp', 'In App')], default='InApp', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('opt_out_whatsapp', models.BooleanField(default=False)),
                ('opt_out_sms', models.BooleanField(default=False)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_report', models.JSONField(default=list)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_name', models.CharField(max_length=255)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation_source', models.CharField(blank=True, max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variety_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sowing_date', models.DateField()),
                ('expected_next_stage_date', models.DateField(blank=True, null=True)),
                ('previous_crop', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='core.cropmaster')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropstage')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('Video', 'Video'), ('Image', 'Image'), ('PDF', 'PDF'), ('Link', 'Link')], max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('language_tags', models.JSONField(blank=True, default=list)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active', max_length=20)),
                ('whatsapp_template', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_template', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_tags', models.ManyToManyField(blank=True, to='core.cropmaster')),
                ('stage_tags', models.ManyToManyField(blank=True, to='core.cropstage')),
            ],
        ),
        migrations.CreateModel(
            name='BulkSendBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('farmer_ids', models.JSONField(default=list)),
                ('recipient_count', models.IntegerField(default=0)),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS')], max_length=20)),
                ('approval_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('send_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promotionlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('timing', models.CharField(max_length=255)),
                ('application_method', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS')], max_length=20)),
                ('send_status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Sent', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropmaster')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.farmer')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropstage')),
            ],
        ),
        migrations.CreateModel(
            name='StageChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='core.cropstage')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_changes', to='core.cropseason')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_to', to='core.cropstage')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active', max_length=20)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_territories', to=settings.AUTH_USER_MODEL)),
                ('parent_territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_territories', to='core.territory')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.territory'),
        ),
        migrations.AddField(
            model_name='user',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.territory'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Visit', 'Visit'), ('Call', 'Call')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('visit_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(choices=[('Pending', 'Pending'), ('Synced', 'Synced')], default='Synced', max_length=20)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('logged_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_activities', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.farmer')),
            ],
            options={
                'unique_together': {('farmer', 'logged_by_user', 'date', 'time', 'activity_type')},
            },
        ),
    ]
