# Generated by Django 5.2.13 on 2026-04-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productmaster_promotionlibrary_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionlibrary',
            name='crop_tags',
        ),
        migrations.RemoveField(
            model_name='promotionlibrary',
            name='stage_tags',
        ),
        migrations.AddField(
            model_name='promotionlibrary',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropmaster'),
        ),
        migrations.AddField(
            model_name='promotionlibrary',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropstage'),
        ),
    ]
